
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { useEffect, useState } from 'react';

export default function TermsOfServicePage() {
  const [lastUpdated, setLastUpdated] = useState('');

  useEffect(() => {
    setLastUpdated(new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }));
  }, []);

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow container max-w-screen-lg mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
        <h1 className="font-headline text-3xl sm:text-4xl font-bold text-primary mb-8 text-center">Terms of Service for iWills.in</h1>
        <div className="prose prose-lg max-w-none text-foreground/80 space-y-6">
          <p>Please read these Terms of Service (&quot;Terms&quot;, &quot;Terms of Service&quot;) carefully before using the iWills.in website (the &quot;Service&quot;) operated by iWills.in (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;).</p>
          
          <p>Your access to and use of the Service for creating Wills online in India is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-8">1. Use of Service</h2>
          <p>The information and tools provided by iWills.in, including its AI Will Assistant, are for assisting in the creation of a Will document based on information you provide and general principles of Indian succession law. It does not constitute legal advice from a lawyer. No attorney-client relationship is formed by your use of this Service.</p>
          <p>You agree not to use the Service:</p>
          <ul>
            <li>In any way that violates any applicable Indian national or local law or regulation.</li>
            <li>For any purpose other than the creation of a personal Will for yourself or as explicitly permitted.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material unrelated to iWills.in services.</li>
          </ul>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">2. AI Will Assistant</h2>
          <p>The AI Will Assistant is a tool designed to provide preliminary information and guidance on Will creation in India. It is not a substitute for advice from a qualified legal professional in India. The responses generated by the AI are based on patterns in data and general legal information, and may not cover all specific nuances of your situation or be accurate, complete, or current for every individual case. You should not rely solely on the AI Will Assistant for complex legal decisions.</p>
          
          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">3. Intellectual Property</h2>
          <p>The Service and its original content (excluding user-provided data for Will creation), features, and functionality are and will remain the exclusive property of iWills.in and its licensors. The Service is protected by copyright, trademark, and other laws of India.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">4. Limitation of Liability</h2>
          <p>In no event shall iWills.in, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service for Will creation; (ii) any errors or omissions in the Will document generated based on your inputs; (iii) any conduct or content of any third party on the Service; (iv) any content obtained from the Service; and (v) unauthorized access, use or alteration of your transmissions or content. Your use of the Service is an acknowledgement that Will creation involves complexities and the service is a tool to assist you, not a replacement for professional legal review if your situation is complex.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">5. Disclaimer</h2>
          <p>Your use of the Service is at your sole risk. The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. The Service is provided without warranties of any kind, express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose (including compliance with all aspects of Indian succession law for every individual situation), non-infringement or course of performance.</p>
          <p>iWills.in does not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected immediately; c) the Service is free of viruses or other harmful components; or d) the results of using the Service (i.e., the generated Will) will meet all your specific legal requirements in India without independent review if your circumstances are complex.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">6. Governing Law</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes arising will be subject to the exclusive jurisdiction of the courts in India.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">7. Changes</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">8. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at contact@iwills.in.</p>

          <p className="mt-8"><em>These are placeholder terms of service. iWills.in strongly advises consulting with a legal professional in India to create terms appropriate for your specific online Will creation services.</em></p>
          <p>Last updated: {lastUpdated || new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
