
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

export default function TermsOfServicePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow container max-w-screen-lg mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
        <h1 className="font-headline text-3xl sm:text-4xl font-bold text-primary mb-8 text-center">Terms of Service</h1>
        <div className="prose prose-lg max-w-none text-foreground/80 space-y-6">
          <p>Please read these Terms of Service (&quot;Terms&quot;, &quot;Terms of Service&quot;) carefully before using the iWills LegalEase website (the &quot;Service&quot;) operated by iWills LegalEase (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;).</p>
          
          <p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-8">1. Use of Service</h2>
          <p>The information provided by iWills LegalEase, including through its AI Legal Assistant, is for general informational purposes only and does not constitute legal advice. No attorney-client relationship is formed by your use of this Service or by communicating with us through this Service.</p>
          <p>You agree not to use the Service:</p>
          <ul>
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any &quot;junk mail&quot;, &quot;chain letter,&quot; &quot;spam,&quot; or any other similar solicitation.</li>
          </ul>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">2. AI Legal Assistant</h2>
          <p>The AI Legal Assistant is a tool designed to provide preliminary information on legal topics. It is not a substitute for advice from a qualified legal professional. The responses generated by the AI are based on patterns in data and may not be accurate, complete, or current. You should not rely on the AI Legal Assistant for any legal decisions.</p>
          
          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">3. Intellectual Property</h2>
          <p>The Service and its original content, features, and functionality are and will remain the exclusive property of iWills LegalEase and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">4. Limitation of Liability</h2>
          <p>In no event shall iWills LegalEase, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii. any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">5. Disclaimer</h2>
          <p>Your use of the Service is at your sole risk. The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>
          <p>iWills LegalEase does not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">6. Governing Law</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which iWills LegalEase operates, without regard to its conflict of law provisions.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">7. Changes</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

          <h2 className="font-headline text-2xl font-semibold text-primary mt-6">8. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at contact@iwillsegalease.com.</p>

          <p className="mt-8"><em>These are placeholder terms of service. Consult with a legal professional to create terms appropriate for your specific services and jurisdiction.</em></p>
          <p>Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
